<?php

/**
 * @var string $urlId
 * @var string $siteUrl
 * @var string $created
 * @var array $checks
 */

?>

<main>
    <div class="container">


        <div class="row mt-5">
            <h2 class="p-0">Сайт: <?= $siteUrl; ?></h2>
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tr>
                    <td>ID</td>
                    <td><?= $urlId; ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $siteUrl; ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $created; ?></td>
                </tr>
            </table>
        </div>

        <div class="row mt-3">
            <h3 class="p-0">Проверки</h3>
            <form method="post" class="p-0"
                  action="<?= $this->getAttribute('routes')->urlFor('urls.checks.store', ['url_id' => $urlId]); ?>">
                <button type="submit" class="btn btn-primary col-2 mt-2">Запустить проверку</button>
            </form>
            <table class="table table-bordered table-hover mt-3" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($checks as $check): ?>
                    <tr>
                        <td><?= $check['id']; ?></td>
                        <td><?= $check['status_code']; ?></td>
                        <td><?= $check['h1']; ?></td>
                        <td><?= $check['title']; ?></td>
                        <td><?= $check['description']; ?></td>
                        <td><?= $check['created_at']; ?></td>
                    </tr>
                <?php
                endforeach; ?>
                </tbody>
            </table>
        </div>


    </div>
</main>
