<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</head>
<body class="">

<header>

    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand px-3" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>

<main>
    <div class="container">
        <div class="row justify-content-md-center mt-3">
            <div class="col-md-8 bg-secondary-subtle px-5 py-5 border border-dark-subtle rounded">
                <h1 class="title fw-normal">Анализатор страниц</h1>
                <p class="slogan fs-4 fw-light">Бесплатно проверяйте сайты на SEO пригодность</p>


                <form class="row g-3" method="post" action="/urls" name="forma">
                    <div class="mb-3 col-8">
                        <label for="adress" class="visually-hidden">Адрес сайта</label>
                        <input type="text" class="form-control" id="adress"
                               aria-describedby="emailHelp" placeholder="url" name="url">
                    </div>
                    <div class="col-3">
                        <button type="submit" class="btn btn-primary">Проверить</button>
                    </div>
                </form>

            </div>
        </div>

    </div>
</main>

</body>
</html>
