<?php
/** @var array $flash */
/** @var string $error */
?>
<?= $this->fetch('header.phtml') ?>
<?php
if (!empty($flash)): ?>
    <div class="alert alert-danger" role="alert">
        <?= $flash['error'][0]; ?>
    </div>
<?php
endif; ?>

<main>
    <div class="container">
        <div class="row justify-content-md-center mt-3">
            <div class="col-md-8 bg-secondary-subtle px-5 py-5 border border-dark-subtle rounded">
                <h1 class="title fw-normal">Анализатор страниц</h1>
                <p class="slogan fs-4 fw-light">Бесплатно проверяйте сайты на SEO пригодность</p>


                <form class="row g-3" method="post" action="/urls" name="forma">
                    <div class="mb-3 col-8">
                        <label for="adress" class="visually-hidden">Адрес сайта</label>
                        <input type="text" class="form-control <?= isset($error) ? 'is-invalid' : ''; ?>"
                               placeholder="url"
                               name="url[name]"
                               id="adress">
                        <div class="invalid-feedback"><?= $error ?? ''; ?></div>
                    </div>
                    <div class="col-3">
                        <input type="submit" class="btn btn-primary" value="Проверить">
                    </div>
                </form>


            </div>
        </div>

    </div>
</main>

<script>

</script>

</body>
</html>
