<?= $this->fetch('header.phtml') ?>

<main>
    <div class="container">
        <div class="row justify-content-md-center mt-3">
            <div class="col-md-8 bg-secondary-subtle px-5 py-5 border border-dark-subtle rounded">
                <h1 class="title fw-normal">Анализатор страниц</h1>
                <p class="slogan fs-4 fw-light">Бесплатно проверяйте сайты на SEO пригодность</p>


                <form class="row g-3" method="post" action="/urls" name="forma">
                    <div class="mb-3 col-8">
                        <label for="adress" class="visually-hidden">Адрес сайта</label>
                        <input type="text" class="form-control" id="adress"
                               aria-describedby="emailHelp" placeholder="url" name="url">
                    </div>
                    <div class="col-3">
                        <button type="submit" class="btn btn-primary">Проверить</button>
                    </div>
                </form>

            </div>
        </div>

    </div>
</main>

</body>
</html>
