<?php

/**
 * @var string $id
 * @var string $siteUrl
 * @var string $created
 *
 * @var string $code
 * @var string $h1
 * @var string $title
 * @var string $descript
 * @var string $data
 */

$code = $h1 = $title = $descript = $data = '%%$%%';
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</head>
<body class="">

<header>

    <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand px-3" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="#">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Сайты</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

</header>

<main>
    <div class="container">


        <div class="row mt-5">
            <h2 class="p-0">Сайт: <?= $siteUrl; ?></h2>
            <table class="table table-bordered table-hover text-nowrap">
                <tr>
                    <td>ID</td>
                    <td><?= $id; ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $siteUrl; ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $created; ?></td>
                </tr>
            </table>
        </div>

        <div class="row mt-3">
            <h3 class="p-0">Проверки</h3>
            <button type="submit" class="btn btn-primary col-2">Запустить проверку</button>
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><?= $id; ?></td>
                    <td><?= $code; ?></td>
                    <td><?= $h1; ?></td>
                    <td><?= $title; ?></td>
                    <td><?= $descript; ?></td>
                    <td><?= $data; ?></td>
                </tr>
                </tbody>
            </table>
        </div>


    </div>
</main>


</body>
</html>
