<?php

/**
 * @var string $id
 * @var string $siteUrl
 * @var string $created
 * @var array $flash
 *
 * @var string $code
 * @var string $h1
 * @var string $title
 * @var string $descript
 * @var string $data
 */

$code = $h1 = $title = $descript = $data = '%%$%%';
?>
<?= $this->fetch('header.phtml') ?>
<?php
if (!empty($flash)): ?>
    <div class="alert alert-success" role="alert">
        <?= $flash['success'][0]; ?>
    </div>
<?php
endif; ?>

<main>
    <div class="container">


        <div class="row mt-5">
            <h2 class="p-0">Сайт: <?= $siteUrl; ?></h2>
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tr>
                    <td>ID</td>
                    <td><?= $id; ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $siteUrl; ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $created; ?></td>
                </tr>
            </table>
        </div>

        <div class="row mt-3">
            <h3 class="p-0">Проверки</h3>
            <button type="submit" class="btn btn-primary col-2 mt-2">Запустить проверку</button>
            <table class="table table-bordered table-hover mt-3" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>


    </div>
</main>


</body>
</html>
