<?php

/**
 * @var string $url_id
 * @var string $siteUrl
 * @var string $created
 * @var array $flash
 *
 * @var array $checks
 *
 * @var string $check_id
 * @var string $status_code
 * @var string $h1
 * @var string $title
 * @var string $description
 * @var string $date
 */

?>
<?= $this->fetch('header.phtml') ?>
<?php
if (!empty($flash)): ?>
    <div class="alert alert-success" role="alert">
        <?= $flash['success'][0]; ?>
    </div>
<?php
endif; ?>

<main>
    <div class="container">


        <div class="row mt-5">
            <h2 class="p-0">Сайт: <?= $siteUrl; ?></h2>
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tr>
                    <td>ID</td>
                    <td><?= $url_id; ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= $siteUrl; ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= $created; ?></td>
                </tr>
            </table>
        </div>

        <div class="row mt-3">
            <h3 class="p-0">Проверки</h3>
            <form method="post" action="/urls/<?= $url_id; ?>/checks">
                <button type="submit" class="btn btn-primary col-2 mt-2">Запустить проверку</button>
            </form>
            <table class="table table-bordered table-hover mt-3" data-test="checks">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Код ответа</th>
                    <th>h1</th>
                    <th>title</th>
                    <th>description</th>
                    <th>Дата создания</th>
                </tr>
                </thead>
                <tbody>
                <?php
                if (!empty($checks)): ?>
                    <?php
                    foreach ($checks as $check): ?>
                        <tr>
                            <td><?= $check['id']; ?></td>
                            <td><?= $check['status_code']; ?></td>
                            <td><?= $check['h1']; ?></td>
                            <td><?= $check['title']; ?></td>
                            <td><?= $check['description']; ?></td>
                            <td><?= $check['created_at']; ?></td>
                        </tr>
                    <?php
                    endforeach; ?>
                <?php
                endif; ?>
                </tbody>
            </table>
        </div>


    </div>
</main>


</body>
</html>
