<?php

/**
 * @var array $sites
 */

?>
<?= $this->fetch('header.phtml') ?>

<main>
    <div class="container">

        <div class="row mt-5">
            <h2 class="p-0">Сайты</h2>
            <table class="table table-bordered table-hover text-nowrap">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Последняя проверка</th>
                    <th>Код ответа</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($sites as $site): ?>
                    <tr>
                        <td><?= $site['id']; ?></td>
                        <td><a href="<?= $site['name']; ?>" target="_blank"><?= $site['name']; ?></a></td>
                        <td><?= $site['check'] ?? ''; ?></td>
                        <td><?= $site['code'] ?? ''; ?></td>
                    </tr>
                <?php
                endforeach; ?>
                </tbody>


            </table>
        </div>


    </div>
</main>


</body>
</html>
