<?php

/**
 * @var string $id
 * @var string $siteUrl
 * @var string $created
 *
 * @var string $code
 * @var string $h1
 * @var string $title
 * @var string $descript
 * @var string $data
 */

?>
<?= $this->fetch('header.phtml') ?>

<main>
    <div class="container">

        <div class="row mt-5">
            <h2 class="p-0">Сайты</h2>
            <table class="table table-bordered table-hover text-nowrap">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Имя</th>
                    <th>Последняя проверка</th>
                    <th>Код ответа</th>
                </tr>
                </thead>
                <tbody>

                </tbody>


            </table>
        </div>


    </div>
</main>


</body>
</html>
